// Centralized message type constants to prevent typos and improve maintainability
export const MESSAGE_TYPES = {
  // Incoming message types (commands)
  SET_CARD_DATA: 'SET_CARD_DATA',
  CLEAR_CARD_DATA: 'CLEAR_CARD_DATA',
  TRIGGER_ENCRYPT_CARD: 'TRIGGER_ENCRYPT_CARD',
  TRIGGER_CHECKOUT_NEW_CARD: 'TRIGGER_CHECKOUT_NEW_CARD',
  TRIGGER_CHECKOUT_WITH_CARD: 'TRIGGER_CHECKOUT_WITH_CARD',
  GET_COMPONENT_STATE: 'GET_COMPONENT_STATE',

  // Outgoing message types (events)
  MASTERCARD_MASKED_CARDS_CHANGED: 'MASTERCARD_MASKED_CARDS_CHANGED',
  MASTERCARD_COMPONENT_READY: 'MASTERCARD_COMPONENT_READY',
  MASTERCARD_RESPONSE: 'MASTERCARD_RESPONSE'
} as const;

export type MessageType = typeof MESSAGE_TYPES[keyof typeof MESSAGE_TYPES];